spring:
  application:
    name: inno-payment-service

  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017}
    database: ${MONGODB_DATABASE:payment_service}
    representation:
      uuid: standard

random-org:
  base-url: ${RANDOM_ORG_BASE_URL:https://www.random.org}
  timeout-ms: ${RANDOM_ORG_TIMEOUT_MS:5000}
  integers-path: ${RANDOM_ORG_INTEGERS_PATH:/integers?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new}